version: '2'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_DAABASE=items
    ports:
      - "27017:27017"

  memcached:
    container_name: cache
    image: memcached:1.6.16
    ports:
      - "11211:11211"

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5671:5671"
      - "5672:5672"
      - "8080:15672"
    volumes:
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 5s
      retries: 30

  solr:
    container_name: solr
    image: solr
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - items

  items:
    build: ./services/items
    depends_on:
      - mongo
      - memcached
      - rabbit
    ports:
      - "8090:8090"

 

  admin:
    build: ./admin
    ports:
      - "8000:8000"
  lbbusqueda:
    build: ./configs/lb
    ports:
      - "80:80"

  items_worker:
    build: ./services/items_worker
    depends_on:
      - lbbusqueda

  solr_worker:
    build: ./services/solr_worker
    depends_on:
      - lbbusqueda
